# Generated by Django 5.2.13 on 2026-05-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'Asset_Classes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('kind', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], max_length=8)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=60)),
                ('display_name', models.CharField(max_length=80)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User_Auth',
            },
        ),
        migrations.CreateModel(
            name='AssetPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('cost_basis', models.DecimalField(decimal_places=4, max_digits=19)),
                ('acquired_at', models.DateField()),
                ('asset_class', models.ForeignKey(db_column='asset_class_id', on_delete=django.db.models.deletion.PROTECT, to='api.assetclass')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.userauth')),
            ],
            options={
                'db_table': 'Asset_Portfolio',
            },
        ),
        migrations.CreateModel(
            name='AssetPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('recorded_at', models.DateTimeField()),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, to='api.assetportfolio')),
            ],
            options={
                'db_table': 'Asset_Price_History',
            },
        ),
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('horizon_months', models.PositiveSmallIntegerField(default=6)),
                ('projected_spend', models.DecimalField(decimal_places=4, max_digits=19)),
                ('projected_income', models.DecimalField(decimal_places=4, max_digits=19)),
                ('runway_months', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('method', models.CharField(max_length=40)),
                ('params', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.userauth')),
            ],
            options={
                'db_table': 'Forecast_Snapshots',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('txn_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=180, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.userauth')),
            ],
            options={
                'db_table': 'Transactions',
                'indexes': [models.Index(fields=['user', '-txn_date'], name='idx_txn_user_date'), models.Index(fields=['user', 'category'], name='idx_txn_user_cat')],
            },
        ),
    ]
