# Generated by Django 5.2.13 on 2026-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='password_hash',
            field=models.CharField(max_length=128),
        ),
    ]
